version: '3'

services:

    scheduled-delivery:
        build: ./ScheduledDeliveryWebApplication
        ports:
          - "8000:5000"
        depends_on:
          - ifood-mock-api
        restart: always
        environment:
          IFOOD_ENDPOINT: http://ifood-mock-api

    ifood-mock-api:
        build: ./IfoodMockAPI
        ports:
          - "8080:5000"
        restart: always
